"""
UP2CLOUD Model - Integration Module
Adds Slack/Teams chatbot, webhook support, and document processing.
"""

import json
from typing import Optional, Dict, Any
from enum import Enum


class ChatbotPlatform(Enum):
    """Supported chatbot platforms."""
    SLACK = "slack"
    TEAMS = "teams"
    DISCORD = "discord"


class SlackIntegration:
    """Slack chatbot integration for UP2CLOUD model."""
    
    @staticmethod
    def format_response(model_response: str, metadata: Dict = None) -> Dict:
        """Format model response as Slack message block."""
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "☁️ UP2CLOUD Cloud Engineering Assistant"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": model_response
                }
            }
        ]
        
        if metadata:
            blocks.append({
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"_Generated by: {metadata.get('model', 'UP2CLOUD')} | Category: {metadata.get('category', 'General')}_"
                    }
                ]
            })
        
        # Action buttons
        blocks.append({
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "👍 Helpful"},
                    "value": "helpful"
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "👎 Not Helpful"},
                    "value": "not_helpful"
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "📊 Get Estimate"},
                    "value": "estimate"
                }
            ]
        })
        
        return {"blocks": blocks}
    
    @staticmethod
    def handle_slash_command(command: str, text: str) -> Dict:
        """Handle Slack slash commands."""
        commands = {
            "/cloud-help": "Get cloud engineering guidance",
            "/estimate-cost": "Get cost estimation for infrastructure",
            "/generate-terraform": "Generate Terraform code",
            "/architecture": "Get architecture recommendations",
            "/security-check": "Perform security audit",
        }
        
        if command in commands:
            return {
                "response_type": "in_channel",
                "text": f"Processing: {commands[command]}",
                "thread_ts": None
            }
        
        return {
            "response_type": "ephemeral",
            "text": "Unknown command. Available commands: " + ", ".join(commands.keys())
        }
    
    @staticmethod
    def handle_message(channel: str, user_id: str, text: str) -> Dict:
        """Handle incoming Slack messages."""
        return {
            "thread_ts": None,
            "text": f"Processing your question about: {text[:50]}...",
            "metadata": {
                "event_type": "message",
                "event_payload": {
                    "type": "cloud_engineering_query"
                }
            }
        }


class TeamsIntegration:
    """Microsoft Teams chatbot integration for UP2CLOUD model."""
    
    @staticmethod
    def format_response(model_response: str, metadata: Dict = None) -> Dict:
        """Format model response as Teams adaptive card."""
        card = {
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.4",
            "body": [
                {
                    "type": "Container",
                    "style": "accent",
                    "items": [
                        {
                            "type": "ColumnSet",
                            "columns": [
                                {
                                    "width": "auto",
                                    "items": [
                                        {
                                            "type": "Image",
                                            "url": "https://via.placeholder.com/40",
                                            "size": "Small"
                                        }
                                    ]
                                },
                                {
                                    "width": "stretch",
                                    "items": [
                                        {
                                            "type": "TextBlock",
                                            "text": "UP2CLOUD Cloud Engineering Assistant",
                                            "weight": "Bolder",
                                            "size": "Large"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "type": "TextBlock",
                    "text": model_response,
                    "wrap": True
                }
            ],
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "👍 Helpful",
                    "url": "https://up2cloud.com/feedback?response=helpful"
                },
                {
                    "type": "Action.OpenUrl",
                    "title": "📊 Get Estimate",
                    "url": "https://up2cloud.com/estimate"
                },
                {
                    "type": "Action.OpenUrl",
                    "title": "💬 Contact Support",
                    "url": "https://up2cloud.com/contact"
                }
            ]
        }
        
        return {
            "type": "message",
            "attachments": [
                {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "contentUrl": None,
                    "content": card
                }
            ]
        }
    
    @staticmethod
    def handle_message(channel_id: str, user_id: str, text: str) -> Dict:
        """Handle incoming Teams messages."""
        return {
            "type": "message",
            "from": {
                "id": "28:123456",
                "name": "UP2CLOUD Bot"
            },
            "conversation": {
                "id": channel_id
            },
            "recipient": {
                "id": user_id
            },
            "text": f"Processing: {text}",
            "timestamp": "2024-01-01T00:00:00Z",
            "serviceUrl": "https://teams.microsoft.com"
        }


class DocumentProcessor:
    """Process infrastructure files and documents."""
    
    @staticmethod
    def analyze_terraform_file(file_content: str) -> Dict[str, Any]:
        """Analyze Terraform configuration file."""
        analysis = {
            "resources_found": [],
            "variables": [],
            "outputs": [],
            "recommendations": [],
            "security_issues": []
        }
        
        # Simple parsing (in production, use HCL parser)
        lines = file_content.split('\n')
        
        for line in lines:
            if 'resource "' in line:
                resource_type = line.split('"')[1]
                analysis["resources_found"].append(resource_type)
            elif 'variable "' in line:
                var_name = line.split('"')[1]
                analysis["variables"].append(var_name)
            elif 'output "' in line:
                output_name = line.split('"')[1]
                analysis["outputs"].append(output_name)
        
        # Generate recommendations
        if "aws_security_group" in analysis["resources_found"]:
            if not any("ingress" in line for line in lines):
                analysis["security_issues"].append("⚠️ Security group with no ingress rules")
        
        if "aws_db_instance" in analysis["resources_found"]:
            if not any("publicly_accessible = false" in line for line in lines):
                analysis["security_issues"].append("🔴 RDS instance may be publicly accessible")
        
        return analysis
    
    @staticmethod
    def analyze_docker_file(file_content: str) -> Dict[str, Any]:
        """Analyze Dockerfile for best practices."""
        analysis = {
            "base_image": None,
            "stages": [],
            "recommendations": [],
            "security_issues": []
        }
        
        lines = file_content.split('\n')
        
        for line in lines:
            if line.startswith('FROM'):
                analysis["base_image"] = line.split()[1]
            elif line.startswith('RUN') or line.startswith('COPY'):
                analysis["stages"].append(line[:50])
        
        # Best practices checks
        if analysis["base_image"]:
            if "latest" in analysis["base_image"]:
                analysis["recommendations"].append("⚠️ Use specific version tags instead of 'latest'")
            if "alpine" not in analysis["base_image"]:
                analysis["recommendations"].append("💡 Consider using Alpine Linux for smaller images")
        
        if not any("USER" in line for line in lines):
            analysis["security_issues"].append("🔴 Container runs as root (no USER directive)")
        
        return analysis
    
    @staticmethod
    def analyze_kubernetes_manifest(file_content: str) -> Dict[str, Any]:
        """Analyze Kubernetes manifest for best practices."""
        try:
            import yaml
            manifest = yaml.safe_load(file_content)
        except:
            return {"error": "Invalid YAML"}
        
        analysis = {
            "kind": manifest.get("kind"),
            "name": manifest.get("metadata", {}).get("name"),
            "containers": [],
            "recommendations": [],
            "security_issues": []
        }
        
        spec = manifest.get("spec", {})
        template = spec.get("template", {})
        containers = template.get("spec", {}).get("containers", [])
        
        for container in containers:
            analysis["containers"].append(container.get("name"))
            
            # Check resource limits
            if "resources" not in container:
                analysis["recommendations"].append("💡 Define resource requests and limits")
            
            # Check security context
            if "securityContext" not in container:
                analysis["security_issues"].append("⚠️ No security context defined")
            
            # Check for latest tag
            image = container.get("image", "")
            if "latest" in image:
                analysis["security_issues"].append(f"🔴 Image '{image}' uses 'latest' tag")
        
        return analysis


class WebhookHandler:
    """Handle incoming webhooks and async processing."""
    
    @staticmethod
    def create_webhook(endpoint_url: str, events: list) -> Dict:
        """Create a webhook subscription."""
        return {
            "webhook_id": f"wh_{hash(endpoint_url) % 10**8}",
            "endpoint": endpoint_url,
            "events": events,
            "status": "active",
            "created_at": "2024-01-01T00:00:00Z",
            "retry_policy": {
                "max_retries": 3,
                "backoff": "exponential"
            }
        }
    
    @staticmethod
    def deliver_event(event: Dict, webhook_url: str) -> Dict:
        """Deliver event to webhook endpoint."""
        return {
            "event_id": event.get("id"),
            "webhook_url": webhook_url,
            "status": "pending",
            "delivery_attempt": 1,
            "max_attempts": 3
        }


class DocumentUploadHandler:
    """Handle document uploads for analysis."""
    
    SUPPORTED_FORMATS = {
        ".tf": "Terraform",
        ".yaml": "Kubernetes Manifest",
        ".yml": "Kubernetes Manifest",
        ".json": "CloudFormation/JSON",
        "Dockerfile": "Docker",
        ".py": "Python Script",
        ".sh": "Shell Script"
    }
    
    @staticmethod
    def process_upload(file_name: str, file_content: str) -> Dict[str, Any]:
        """Process uploaded file and return analysis."""
        analysis = {
            "file_name": file_name,
            "file_type": None,
            "analysis": None,
            "status": "processed"
        }
        
        # Determine file type
        for extension, file_type in DocumentUploadHandler.SUPPORTED_FORMATS.items():
            if file_name.endswith(extension) or file_name == extension:
                analysis["file_type"] = file_type
                break
        
        if not analysis["file_type"]:
            analysis["status"] = "unsupported"
            return analysis
        
        # Route to appropriate analyzer
        if analysis["file_type"] == "Terraform":
            analysis["analysis"] = DocumentProcessor.analyze_terraform_file(file_content)
        elif analysis["file_type"] == "Kubernetes Manifest":
            analysis["analysis"] = DocumentProcessor.analyze_kubernetes_manifest(file_content)
        elif analysis["file_type"] == "Docker":
            analysis["analysis"] = DocumentProcessor.analyze_docker_file(file_content)
        
        return analysis


if __name__ == "__main__":
    print("UP2CLOUD Integration Module")
    print("=" * 60)
    
    # Test Slack Integration
    print("\n1. Slack Integration:")
    slack_response = SlackIntegration.format_response(
        "Here are the best practices for optimizing your AWS costs...",
        {"model": "UP2CLOUD", "category": "FinOps"}
    )
    print(f"   Formatted for Slack: {len(slack_response['blocks'])} blocks")
    
    # Test Teams Integration
    print("\n2. Teams Integration:")
    teams_response = TeamsIntegration.format_response(
        "Here are recommendations for your Kubernetes migration..."
    )
    print(f"   Formatted for Teams: Adaptive Card created")
    
    # Test Document Upload
    print("\n3. Document Upload:")
    tf_content = 'resource "aws_vpc" "main" { cidr_block = "10.0.0.0/16" }'
    upload_result = DocumentUploadHandler.process_upload("main.tf", tf_content)
    print(f"   Processed: {upload_result['file_name']} ({upload_result['file_type']})")
    
    # Test Webhook Handler
    print("\n4. Webhook Handler:")
    webhook = WebhookHandler.create_webhook(
        "https://example.com/webhook",
        ["cost-update", "security-alert"]
    )
    print(f"   Webhook ID: {webhook['webhook_id']}")
    print(f"   Status: {webhook['status']}")
